### ISSUE TITLE
Using flexbox, try to fix the navigation @desktop to have logo on the left and navigation links on the right.

### ISSUE THREAD

**Issue by ekaiser93** [TigerLady27/cat_costume_project#2]
https://github.com/TigerLady27/cat_costume_project/blob/3eb895135d1450119daf5635293214100edf7666/index.html#L10-L16

You can fix this section by making the parent class (nav) display flex and justify space between.  Looks like you tried to do this on the child (nav div) in your css.  We can go over this Wednesday if my explanation is confusing. :)

**Comment by TigerLady27** [comment]
flex box the nav

**Comment by TigerLady27** [comment]
Fixed
