### ISSUE TITLE
These two classes can be the same instead of separated out into two classes.  Try to fix with one class used for each box.

### ISSUE THREAD

**Issue by ekaiser93** [TigerLady27/cat_costume_project#7]
https://github.com/TigerLady27/cat_costume_project/blob/3eb895135d1450119daf5635293214100edf7666/index.html#L65, https://github.com/TigerLady27/cat_costume_project/blob/3eb895135d1450119daf5635293214100edf7666/index.html#L73

**Comment by TigerLady27** [comment]
Make contact 1 & 2 one DIV

**Comment by TigerLady27** [comment]
fixed
